param(
    [string]$Bo3Path,
    [string]$T7ExePath,
    [switch]$EnableItemQuantity
)

$ErrorActionPreference = 'Stop'

function Get-RepoRoot {
    Split-Path -Parent $PSCommandPath
}

function Get-SourceDllPath {
    $repoRoot = Get-RepoRoot
    $candidates = @(
        (Join-Path $repoRoot 'd3d11.dll'),
        (Join-Path $repoRoot 'src\x64\Release\d3d11.dll')
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            return $candidate
        }
    }

    throw "d3d11.dll was not found next to install.ps1 or in src\\x64\\Release. Build or copy the DLL first."
}

function Get-SteamLibraryFolders {
    $steamRoot = Join-Path ${env:ProgramFiles(x86)} 'Steam'
    $libraryVdf = Join-Path $steamRoot 'steamapps\libraryfolders.vdf'
    $paths = New-Object System.Collections.Generic.List[string]

    if (Test-Path $steamRoot) {
        $paths.Add($steamRoot)
    }

    if (Test-Path $libraryVdf) {
        $matches = Select-String -Path $libraryVdf -Pattern '"path"\s*"([^"]+)"'
        foreach ($match in $matches) {
            $value = $match.Matches[0].Groups[1].Value -replace '\\\\', '\'
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                $paths.Add($value)
            }
        }
    }

    return $paths | Select-Object -Unique
}

function Find-Bo3InstallPath {
    foreach ($libraryPath in Get-SteamLibraryFolders) {
        $candidate = Join-Path $libraryPath 'steamapps\common\Call of Duty Black Ops III'
        if (Test-Path (Join-Path $candidate 'BlackOps3.exe')) {
            return $candidate
        }
    }

    return $null
}

function Get-BoolText([bool]$Value) {
    if ($Value) { return 'true' }
    return 'false'
}

function Prompt-Bool {
    param(
        [string]$Prompt,
        [bool]$DefaultValue
    )

    $suffix = if ($DefaultValue) { '[Y/n]' } else { '[y/N]' }
    $response = Read-Host "$Prompt $suffix"

    if ([string]::IsNullOrWhiteSpace($response)) {
        return $DefaultValue
    }

    return $response.Trim().ToLowerInvariant() -in @('y', 'yes')
}

function Get-ConfiguredBo3Path {
    param([string]$InitialValue)

    $candidate = $InitialValue
    if ([string]::IsNullOrWhiteSpace($candidate)) {
        $candidate = Find-Bo3InstallPath
    }

    while ([string]::IsNullOrWhiteSpace($candidate) -or -not (Test-Path (Join-Path $candidate 'BlackOps3.exe'))) {
        $candidate = Read-Host 'Enter your BO3 install folder path'
    }

    return $candidate
}

function Get-ConfiguredT7Path {
    param([string]$InitialValue)

    $candidate = $InitialValue
    if ([string]::IsNullOrWhiteSpace($candidate)) {
        $defaultPath = Join-Path $env:USERPROFILE 't7patch\Current\t7patch_2.04.exe'
        if (Test-Path $defaultPath) {
            $candidate = $defaultPath
        }
    }

    if ([string]::IsNullOrWhiteSpace($candidate)) {
        $shouldConfigureT7 = Prompt-Bool -Prompt 'Create the BO3 Safe launcher with T7Patch support?' -DefaultValue $false
        if (-not $shouldConfigureT7) {
            return $null
        }

        while ([string]::IsNullOrWhiteSpace($candidate) -or -not (Test-Path $candidate)) {
            $candidate = Read-Host 'Enter the full path to t7patch_2.04.exe'
        }
    }

    return $candidate
}

function Backup-File {
    param([string]$Path)

    if (-not (Test-Path $Path)) {
        return $null
    }

    $timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
    $backupPath = "$Path.backup_$timestamp"
    Copy-Item -Force $Path $backupPath
    return $backupPath
}

function Set-Bo3Config {
    param(
        [string]$ConfigPath,
        [bool]$OverrideItemQuantity,
        [int]$ItemQuantity
    )

    $configText = @"
; BO3 Safe Fork configuration
; Generated by install.ps1
; Restart BO3 after changing this file.

[core]
; show_startup_popup: shows the module startup popup from the original project.
show_startup_popup=false
; enable_debug_logging: writes bo3_patch.log next to the DLL for local diagnostics.
; Leave this false in normal use.
enable_debug_logging=false
; enable_crc: preserves the original debug-register hook activation path.
enable_crc=true
; enable_presence: keeps the handshake-related Live_PresenceParty patch enabled.
enable_presence=true
; enable_instant_message: keeps the original instant message filter hook enabled.
enable_instant_message=true
; enable_out_of_band: keeps the original out-of-band voice packet filter hook enabled.
enable_out_of_band=true
; memory_threshold_bytes: wait until BO3 reaches this private memory size before installing hooks.
memory_threshold_bytes=3145728000

[inventory]
; override_item_quantity: enables the original quantity override hook.
; Leave this false for legit-safe play.
override_item_quantity=$(Get-BoolText $OverrideItemQuantity)
; item_quantity: value returned by the quantity override hook when enabled.
item_quantity=$ItemQuantity
; unlock_item_attachments: unlocks attachment count and attachment lock checks.
unlock_item_attachments=false
; unlock_challenge_items: unlocks challenge-based item checks.
unlock_challenge_items=false
; unlock_entitlement_backgrounds: unlocks entitlement background checks.
unlock_entitlement_backgrounds=false
; unlock_item_options: unlocks item option lock checks.
unlock_item_options=false
; unlock_item_purchases: bypasses purchase checks.
unlock_item_purchases=false
; unlock_character_customization: unlocks character customization checks.
unlock_character_customization=false
; unlock_emblems_from_challenges: unlocks emblem/backing challenge checks.
unlock_emblems_from_challenges=false
"@

    if (Test-Path $ConfigPath) {
        Backup-File -Path $ConfigPath | Out-Null
    }

    Set-Content -Path $ConfigPath -Value $configText -Encoding Ascii
}

function New-LauncherText {
    param(
        [string]$Bo3Path,
        [string]$T7ExePath,
        [string]$T7ProcessName,
        [bool]$UseT7
    )

    $bo3Dir = ($Bo3Path | Select-Object -First 1).ToString().Trim()
    $t7Line = ''
    $t7Check = ''
    $trimmedT7ExePath = ''
    $trimmedT7ProcessName = ''

    if (-not [string]::IsNullOrWhiteSpace($T7ExePath)) {
        $trimmedT7ExePath = ($T7ExePath | Select-Object -First 1).ToString().Trim()
    }

    if (-not [string]::IsNullOrWhiteSpace($T7ProcessName)) {
        $trimmedT7ProcessName = ($T7ProcessName | Select-Object -First 1).ToString().Trim()
    }

    if ($UseT7) {
        $t7Line = ('set "T7_EXE={0}"' -f $trimmedT7ExePath)
        $t7Check = @(
            'if not exist "%T7_EXE%" (',
            '  echo [ERROR] T7Patch not found at:',
            '  echo %T7_EXE%',
            '  pause',
            '  exit /b 1',
            ')',
            '',
            ('tasklist /FI "IMAGENAME eq {0}" | find /I "{0}" >nul' -f $trimmedT7ProcessName),
            'if errorlevel 1 (',
            '  start "" "%T7_EXE%"',
            '  timeout /t 3 /nobreak >nul',
            ')',
            ''
        ) -join "`r`n"
    }

    return @(
        '@echo off',
        'setlocal',
        '',
        ('set "BO3_DIR={0}"' -f $bo3Dir),
        'set "BO3_EXE=%BO3_DIR%\BlackOps3.exe"',
        'set "PATCH_DLL=%BO3_DIR%\d3d11.dll"',
        $t7Line,
        '',
        'if not exist "%BO3_EXE%" (',
        '  echo [ERROR] BO3 was not found at:',
        '  echo %BO3_EXE%',
        '  pause',
        '  exit /b 1',
        ')',
        '',
        'if not exist "%PATCH_DLL%" (',
        '  echo [ERROR] Custom d3d11.dll was not found at:',
        '  echo %PATCH_DLL%',
        '  pause',
        '  exit /b 1',
        ')',
        '',
        $t7Check,
        'start "" "steam://run/311210"',
        '',
        'exit /b 0'
    ) -join "`r`n"
}

function Write-Launcher {
    param(
        [string]$Path,
        [string]$Text
    )

    Set-Content -Path $Path -Value $Text -Encoding Ascii
}

$sourceDllPath = Get-SourceDllPath
$Bo3Path = Get-ConfiguredBo3Path -InitialValue $Bo3Path
$T7ExePath = Get-ConfiguredT7Path -InitialValue $T7ExePath

$enableQuantity = $EnableItemQuantity.IsPresent
if (-not $PSBoundParameters.ContainsKey('EnableItemQuantity')) {
    $enableQuantity = Prompt-Bool -Prompt 'Enable the item quantity override (useful for GobbleGum-style consumables)?' -DefaultValue $false
}

$destinationDllPath = Join-Path $Bo3Path 'd3d11.dll'
$destinationConfigPath = Join-Path $Bo3Path 'bo3_patch.ini'

if (Test-Path $destinationDllPath) {
    $sourceHash = (Get-FileHash -Algorithm SHA256 $sourceDllPath).Hash
    $destinationHash = (Get-FileHash -Algorithm SHA256 $destinationDllPath).Hash

    if ($sourceHash -ne $destinationHash) {
        Backup-File -Path $destinationDllPath | Out-Null
    }
}

Copy-Item -Force $sourceDllPath $destinationDllPath
Set-Bo3Config -ConfigPath $destinationConfigPath -OverrideItemQuantity $enableQuantity -ItemQuantity 999

$desktopPath = [Environment]::GetFolderPath('Desktop')
$directLauncherPath = Join-Path $desktopPath 'BO3 Direct.cmd'
Write-Launcher -Path $directLauncherPath -Text (New-LauncherText -Bo3Path $Bo3Path -UseT7:$false -T7ExePath '' -T7ProcessName '')

$safeLauncherCreated = $false
if (-not [string]::IsNullOrWhiteSpace($T7ExePath)) {
    $safeLauncherPath = Join-Path $desktopPath 'BO3 Safe.cmd'
    $t7ProcessName = Split-Path -Leaf $T7ExePath
    Write-Launcher -Path $safeLauncherPath -Text (New-LauncherText -Bo3Path $Bo3Path -T7ExePath $T7ExePath -T7ProcessName $t7ProcessName -UseT7:$true)
    $safeLauncherCreated = $true
}

Write-Host ''
Write-Host 'Install complete.'
Write-Host "BO3 path: $Bo3Path"
Write-Host "DLL deployed to: $destinationDllPath"
Write-Host "Config written to: $destinationConfigPath"
Write-Host "Direct launcher: $directLauncherPath"
if ($safeLauncherCreated) {
    Write-Host "Safe launcher: $(Join-Path $desktopPath 'BO3 Safe.cmd')"
}
else {
    Write-Host 'Safe launcher was skipped because T7Patch was not configured.'
}
